[package]
name = "rust_tests_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.11"
criterion = "0.5.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
testdir = "0.8.0"
